Feat: find a delegate by the given address
Adamant-im/adamant pull request #79
Opened 2024-06-20 00:21 UTC by martiliones

[`/delegates/get?address=U12693243886978615076`](https://ahead.adamant.im/api/delegates/get?address=U12693243886978615076)

additionally, optimized `/delegates/get` endpoint to search for a single transaction

Trello: Optimize /delegates/get and add address parameter https://trello.com/c/1OTebrME

2024-09-13 17:14 UTC, adamant-al approved these changes

2024-09-14 01:24 UTC, bludnic requested changes

2024-09-14 01:24 UTC, bludnic commented on modules/delegates.js
> +  }
Is this really necessary? Dynamic function arguments can be confusing.

Just pass undefined if you don't need to apply a filter. I think this approach is more clear.
```js
modules.delegates.getDelegates(query, undefined, cb)
```

2024-09-14 01:24 UTC, bludnic commented on modules/delegates.js
> +  }
A good solution would be to convert the function arguments into an object. This way, you can easily omit the `filter` property if it's not needed. However, this will create significant changes in the codebase so I would stick with the previous approach.

2024-09-14 06:18 UTC, yoxira commented on modules/delegates.js
> +  }
It was made to make sure it doesn't break anything, but it seems like the method is not commonly used.

2024-09-14 17:47 UTC, bludnic commented on modules/delegates.js
> +Delegates.prototype.getDelegates = function (query, filter, cb) {
Can you describe the `filter` param in JSDoc?

2024-10-01 18:39 UTC, bludnic requested changes

2024-10-01 18:39 UTC, bludnic commented on modules/delegates.js
> +        filter.publicKey = req.body.publicKey;
It seems like the find delegate by public key is broken:

http://localhost:36666/api/delegates/get?publicKey=e8ecea9faf2b9cfa26d635bc94d8457114beafc90b4f6b5a7f1354d193ab0f3b

![image](https://github.com/user-attachments/assets/f75167bc-5505-4a68-b7a9-ee8be95ee174)

Although same request on production node works fine:

https://bid.adamant.im/api/delegates/get?publicKey=e8ecea9faf2b9cfa26d635bc94d8457114beafc90b4f6b5a7f1354d193ab0f3b

![image](https://github.com/user-attachments/assets/14de1cda-1f47-460d-a098-26f26c12d82b)

2024-10-01 18:39 UTC, bludnic commented on modules/delegates.js
> +        filter.address = req.body.address;
Shouldn't `req.body` params be sanitized? Is SQL injection possible here? @martiliones

2024-10-08 12:02 UTC, bludnic commented on modules/delegates.js
> +      if (req.body.publicKey) {
GET http://localhost:36666/api/delegates/get?publicKey=qwe

`500 Internal Server Error`
```json
{"success":false,"error":"API error: The argument 'encoding' is invalid for data of length 3. Received 'hex'"}
```

GET https://bid.adamant.im/api/delegates/get?publicKey=qwe

`200 OK`

```json
{"success":false,"nodeTimestamp":224017224,"error":"Delegate not found"}
```

Expected same behaviour. @martiliones

2024-10-10 22:25 UTC, bludnic commented
Don't forget to update the Wiki after merge
https://github.com/Adamant-im/adamant/wiki/API-Specification#get-delegate

2024-11-10 09:46 UTC, adamant-al commented
@yoxira 
Update

2024-11-10 22:15 UTC, yoxira commented on modules/delegates.js
> +      if (req.body.publicKey) {
Added validation for `publicKey` and `address` properties. It's not the same as `Delegate not found` but the right way to handle this, in my opinion.

2024-11-11 05:08 UTC, bludnic commented
Please update also schema.adamant.im @yoxira

2024-11-11 20:20 UTC, yoxira commented
@bludnic 
https://github.com/Adamant-im/adamant-schema/pull/15

2024-11-11 20:45 UTC, bludnic approved these changes

2024-11-11 20:46 UTC, merged