Feat/ws transaction types
Adamant-im/adamant pull request #80
Opened 2024-06-20 00:56 UTC by martiliones

### Fixed
- A memory leak when subscribing to multiple addresses
- A bug when the websocket would send a transaction that has address which starts with the subscribed address 

### Added

Usage:

```js
// w/o an address
socket.emit('types', [TransactionType.SEND, TransactionType.CHAT_MESSAGE]);
socket.on('newTrans', console.log.bind('Chat transaction without bounding to a specific address:'));
```
```js
// w/ an address
socket.emit('address', 'U1234567890123456');
socket.emit('types', [TransactionType.SEND, TransactionType.CHAT_MESSAGE]);
socket.on('newTrans', console.log.bind('Chat transaction for the user:'));

```

2024-06-21 10:33 UTC, adamant-al commented
@martiliones 
Create a Trello card for the task

2024-09-13 17:18 UTC, adamant-al commented
> should we allow unsubscribing from types?

Provide a reason and an example.

2024-09-14 18:00 UTC, bludnic commented
> you can test using the following code snippet and `ahead` node:
> 
> ```js
> import {io} from 'socket.io-client';
> 
> const connection = io('https://ahead.adamant.im/', {
>   reconnection: false,
>   timeout: 5000
> });
> 
> connection.on('connect', () => {
>   console.log('connected');
> 
>   connection.emit('types', [0, 8]);
> });
> 
> connection.on('newTrans', (transaction) => {
>   console.log(transaction)
> });
> 
> connection.on('disconnect', (reason) => {
>   console.log(`disconnected, reason: ${reason}`)
> })
> 
> connection.on('connect_error', error =>
>   console.warn(`connection error: ${error}`)
> );
> ```

It doesn't work for me. After successful connection it does not emit new transactions. Tried to send a message and in-chat transfer.

![image](https://github.com/user-attachments/assets/4bb405f8-f5a3-440a-b33b-e97d0892c9b3)

2024-09-14 18:24 UTC, bludnic commented
As I see previously we could subscribe to several addresses by emitting "address" multiple times, but now since you changed the ID of the subscription this is not possible.

Previously:

```js
import { io } from 'socket.io-client';

const connection = io('https://debate.adamant.im/', {
  reconnection: false,
  timeout: 5000
});

connection.on('connect', () => {
  console.log('connected');

  connection.emit('address', 'U9203183357885757380')
  connection.emit('address', 'U14724553101605161229')
  connection.emit('types', [0, 8]);
});

connection.on('newTrans', (transaction) => {
  console.log(transaction)
});
```

I think using socket.id as an ID is a good approach, but we must keep the previous functionality. Therefore, I suggest passing "address" as an array. To maintain backward compatibility, I would also handle the string value type.

```js
connection.on('connect', () => {
  console.log('connected');

  connection.emit('address', ['U9203183357885757380', 'U14724553101605161229'])
  connection.emit('types', [0, 8]);
});
```

2024-09-14 18:33 UTC, bludnic commented on modules/clientWs.js
> +        };
Can we use an array of numbers for simplicity? What are the benefits of your approach?

2024-09-18 04:50 UTC, yoxira commented on modules/clientWs.js
> +        };
much better memory efficiency and speed, obviously

2024-09-18 04:53 UTC, yoxira commented
> It doesn't work for me

I have reverted the ahead node commits in favor of testing #82

2024-09-18 05:26 UTC, bludnic commented on modules/clientWs.js
> +        };
I agree that is more efficient, but does we really win a lot in this specific case?

2024-09-18 10:46 UTC, adamant-al commented on modules/clientWs.js
> +        };
@yoxira 
Note than soon we'll have more tx types.

2024-09-18 10:48 UTC, adamant-al commented
@yoxira 
See the Testing blockchain dev updates https://docs.google.com/document/d/15LWxiLf6VQin3cT8UFEoJd9mng-sD4JJpr5KP98J82c/edit#heading=h.bmjmb6vgdt7k
Waiting for raising height 0 ⟶ current on the ahead node may take a month. Not acceptable.

2024-09-19 15:01 UTC, yoxira commented on modules/clientWs.js
> +      ([address1, address2].includes(address) && isTypeAllowed) ||
`[address1, address2].includes(address)` doesn't do anything, if it's false then it's just going to pass through because of `|| isTypeAllowed`

2024-09-19 15:03 UTC, yoxira requested changes

2024-09-19 15:03 UTC, yoxira commented on modules/clientWs.js
> +            transactionTypes.forEach((type) => (describe.types |= 1 << type));
this may lead to unsafe integer

2024-09-19 15:03 UTC, yoxira commented on modules/clientWs.js
> +          if (typeof a === 'string') {
use RegExp to test the addresses

2024-09-19 15:03 UTC, yoxira commented on modules/clientWs.js
> +        const describe = {
use class instead?

2024-09-19 15:28 UTC, bludnic commented on modules/clientWs.js
> +        };
Will your solution work if the transaction type cannot be stored in one byte, e.g. `type: 256`?

2024-09-20 04:48 UTC, yoxira commented on modules/clientWs.js
> +        };
It will work using up to 52 bits (=each bit representing transaction type)

2024-09-20 04:51 UTC, yoxira commented on modules/clientWs.js
> +        };
It works for types from `0` to `52`, if we'll ever need a higher type, we can just use bigint

2024-09-20 04:53 UTC, yoxira commented on modules/clientWs.js
> +        };
to save memory I assume we need to filter out invalid types / addresses anyway

2024-09-20 05:53 UTC, bludnic commented on modules/clientWs.js
> +        };
So, if we exceed the value of `52`, we should modify the code to keep it working, right? In that case, using an array of numbers is a universal solution.

2024-09-21 12:19 UTC, yoxira commented on helpers/tranasctionTypesBoundary.js
> +  .filter((type) => typeof type === 'number');
does this look unreliable?

2024-09-21 12:21 UTC, yoxira commented
- Added back subscribing to multiple addresses
- Rewritten to use `Set`

2024-09-21 18:22 UTC, bludnic requested changes

2024-09-21 18:22 UTC, bludnic commented on modules/clientWs/transactionSubscription.js
> +        validator.validate(address, { format: 'address' })
I see that the validator already has a check for [str.length](https://github.com/Adamant-im/adamant/blob/b2f4508c2f23816e423df7ec7c372fcff25bad2d/helpers/z_schema.js#L36).

It may be enough call the validator without additional checks:

```js
if (validator.validate(address, { format: 'address' })) { // ...
```

2024-09-21 18:22 UTC, bludnic commented on modules/clientWs/transactionSubscription.js
> +  }
Add a comment referring to [transactionTypes.js](https://github.com/Adamant-im/adamant/blob/fd4d79f6588e1b729859ea2bc2b8ae86b2d41b89/helpers/transactionTypes.js#L1)

2024-09-21 18:22 UTC, bludnic commented on modules/clientWs/transactionSubscription.js
> +  subscribeToTypes(...types) {
Add JSDoc for `types` argument

2024-09-21 18:22 UTC, bludnic commented on modules/clientWs/transactionSubscription.js
> +  }
Add JSDoc

2024-09-21 18:22 UTC, bludnic commented on test/unit/modules/clientWs.js
> +var TransactionSubscription = require('../../../modules/clientWs/transactionSubscription');
We can use `const` instead `var`

2024-09-21 18:22 UTC, bludnic commented on test/unit/modules/clientWs.js
> +describe('TransactionSubscription', function () {
Consider arrow function. Fix also below

2024-09-21 18:22 UTC, bludnic commented on helpers/tranasctionTypesBoundary.js
> +  .filter((type) => typeof type === 'number');
Seems reliable. Maybe add a note that this is needed only to exclude [CHAT_MESSAGE_TYPES](https://github.com/Adamant-im/adamant/blob/fd4d79f6588e1b729859ea2bc2b8ae86b2d41b89/helpers/transactionTypes.js#L14)

2024-09-22 01:57 UTC, yoxira commented on modules/clientWs/transactionSubscription.js
> +        validator.validate(address, { format: 'address' })
1. it doesn't check for a type (`string`)
2. it has the opposite condition that **allows** empty strings

2024-09-22 02:00 UTC, bludnic commented on modules/clientWs/transactionSubscription.js
> +        validator.validate(address, { format: 'address' })
Do you know why in the validator, an empty string is a valid address?

2024-09-22 02:03 UTC, bludnic commented on modules/clientWs/transactionSubscription.js
> +        validator.validate(address, { format: 'address' })
Maybe it's better to move additional checks in the validator?

2024-09-26 10:40 UTC, bludnic requested changes

2024-09-26 10:40 UTC, bludnic commented on modules/clientWs.js
> +  return subs.filter((sub) =>
`TypeError: subs.filter is not a function`

2024-10-01 18:50 UTC, bludnic commented
```js
import { io } from "socket.io-client";

const connection = io("http://localhost:36668", {
  reconnection: false,
  timeout: 5000,
});

connection.on("connect", () => {
  console.log("connected");

  connection.emit("address", ["U14724553101605161229"]);
  connection.emit("types", [0, 8]);
});

connection.on("newTrans", (transaction) => {
  console.log(transaction);
});
```

I run this code on my local node but cannot receive a `newTrans` event.
Tried to send an ongoing/outgoing message to/from U14724553101605161229 address.

Am I doing it right? @yoxira

2024-10-08 12:23 UTC, bludnic approved these changes

2024-10-08 12:36 UTC, closed without merging