Chore/tests
Adamant-im/adamant pull request #86
Opened 2024-11-07 03:52 UTC by yoxira

2024-11-11 21:43 UTC, bludnic commented on test/unit/logic/state.js
> +      const savePromise = state.dbSave(validTransaction);
Better to avoid such naming, because the return type is no a promise

2024-11-27 02:32 UTC, bludnic requested changes

2024-11-27 02:32 UTC, bludnic commented on test/unit/logic/chat.js
> +describe('Chat', () => {
There are failed tests

![image](https://github.com/user-attachments/assets/6b5f5c45-0698-4d60-9562-7fafe7a710a2)

2024-11-27 02:32 UTC, bludnic commented on test/unit/logic/chat.js
> +    it('should verify okay for valid transaction', (done) => {
```suggestion
    it('should verify for a valid transaction', (done) => {
```

2024-11-27 02:32 UTC, bludnic commented on test/unit/modules/delegates.js
> +const Delegates = require('../../../modules/delegates.js');
This import is not used

2024-11-27 02:32 UTC, bludnic commented on test/unit/modules/transactions.js
> +const Transactions = require('../../../modules/transactions.js');
Import not used

2024-11-27 02:32 UTC, bludnic commented on test/unit/modules/transactions.js
> +describe('transactions', function () {
Some tests failed

![image](https://github.com/user-attachments/assets/5b7d18d1-94f2-4188-b0b4-5bbc51177fa6)

2024-11-27 02:32 UTC, bludnic commented on test/unit/modules/accounts.js
> +      });
Since you added an additional check in `openAccount` method:

https://github.com/Adamant-im/adamant/blob/d493f17446d8ad835c1a419b83daead72a3367db/modules/accounts.js#L97-L101

Add also a test case for `{ secret: "invalid secret"  }`. It must throw "Mnemonic string is invalid:..."

2024-11-27 04:45 UTC, yoxira commented on test/unit/modules/delegates.js
> +const Delegates = require('../../../modules/delegates.js');
it's used for type declaration in jsdoc
```js
describe('delegates', function () {
  /**
   * @type {Delegates}
   */
  let delegates;
```

2024-11-27 07:49 UTC, bludnic approved these changes

2024-12-01 22:58 UTC, yoxira commented
Not ready for a review.

2024-12-10 23:54 UTC, yoxira commented
@adamant-al I think that tests under `test/api` replace the need for "transaction flood script" (https://trello.com/c/T1RLgwVF), as they include stress tests for the transaction types. We will run the `test/api` tests on every new version, and the `test/unit` tests, which don’t require running a local test node, are there for general development.

2024-12-11 00:01 UTC, yoxira commented
Note that the PR aims to fix previous tests, add more unit tests, and resolve issues caused by updating dependencies (#82). Some tests, like `test/api/peer.transactions.votes.js`, may still fail due to unexpected node behavior, _not the mistakes in tests_.

2024-12-11 17:47 UTC, bludnic commented
@yoxira why downgrading `change-case` and `execa` versions? https://github.com/Adamant-im/adamant/pull/86/commits/53c0bc9c198244ae66ee6252a2e1dba69fe6f875

2024-12-11 18:13 UTC, bludnic commented
@yoxira Well done described tests and best practices in [CONTRIBUTING.md](https://github.com/Adamant-im/adamant/pull/86/commits/a3262e5cde357b892643d4c2a33abbad75fffd4b#diff-98e64bc1cd2db9333c6effe87bbe0d6dfe8714aba4c6bde45aa037fe0796e44c) 👍

2024-12-11 18:43 UTC, bludnic requested changes

2024-12-11 18:43 UTC, bludnic commented on modules/accounts.js
> +      return setImmediate(cb, error);
Cover with tests [test/unit/modules/accounts.js](https://github.com/Adamant-im/adamant/blob/82771c92054574922281740e83666fc535afe0c6/test/unit/modules/accounts.js) different scenarios:

1. With fields: 
```js
account.getAccount({ publicKey }, ['balance'], (err) => {})
```
2. Without fields
```js
account.getAccount({ publicKey }, (err) => {})
```
3. Edge cases (e.g. `cb` not provided, or `fields` as non-array)

2024-12-11 18:43 UTC, bludnic commented on modules/accounts.js
> +      return setImmediate(cb, error);
Update also the JSDoc describing different function signatures.
https://austingil.com/typescript-function-overloads-with-jsdoc/

2024-12-11 18:43 UTC, bludnic commented on package.json
> +    "chai": "^4.3.10",
Can you describe the issue with the newer version of `chai`?

2024-12-11 18:43 UTC, bludnic commented on helpers/sequence.js
> +  };
Can you explain why this change? Does it fix a bug? @yoxira 

1. I don't see `nextSequenceTick` to be initially invoked on first run anymore (previously via `setImmediate()`).
2. I think there was a reason in using `setTimeout` (for non-blocking). Without it, it may result in stack overflow.
3. Tests needed.

Better to revert the changes if it does not fix any bug.

2024-12-11 18:43 UTC, bludnic commented on modules/cache.js
> +  cb(null, parsedValue);
You call the `cb()` twice when an error is caught. Is that expected?

2024-12-11 18:43 UTC, bludnic commented on modules/delegates.js
> +          sort: { balance: -1 }
Add unit tests for this case

2024-12-11 18:43 UTC, bludnic commented on package.json
> +    "why-is-node-running": "^2.3.0",
Forgot to remove?

2024-12-11 18:46 UTC, yoxira commented
@bludnic I accidentally bumped them in #82, even though I explicitly wrote the description in the PR:
> We can't bump the chai, change-case and execa package versions as they dropped CommonJS support.

2024-12-11 18:52 UTC, yoxira commented on helpers/sequence.js
> +  };
@bludnic Previously, the tick function ran indefinitely every `N` ms, preventing the process from exiting when the script ended (e.g., after all unit tests passed).

1. It now starts only when a new task is added to the queue, instead of continuously checking for new tasks.
2. It still avoids blocking the event loop, thanks to `setImmediate`.

2024-12-11 19:06 UTC, bludnic commented on helpers/sequence.js
> +  };
I'm wondering if there was a reason for using `setTimeout` + `setImmediate` in previous version. Currently, only `setImmediate` is used. Also, the `setTimeout` had a delay of 3ms previously.

Anyway, since you touched that file, better to cover it with tests.

2024-12-11 19:10 UTC, bludnic commented on helpers/sequence.js
> +  };
Consider whether there may be a scenario in which the queue suddenly stops.

2024-12-11 19:31 UTC, bludnic requested changes

2024-12-11 19:31 UTC, bludnic commented on test/unit/modules/transactions.js
> +describe('transactions', function () {
two tests failed

![image](https://github.com/user-attachments/assets/0d17f46d-b27d-4eb6-8508-eb05d940dd33)

2024-12-11 23:19 UTC, yoxira commented on modules/accounts.js
> +      return setImmediate(cb, error);
The edge cases are not that important because it's an internal method

2024-12-12 01:34 UTC, bludnic commented on modules/accounts.js
> + * @param {function} fields - Callback function.
```suggestion
 * @param {function} cb - Callback function.
```

2024-12-12 01:35 UTC, bludnic approved these changes

2024-12-12 19:53 UTC, merged