feat: disconnect from peers on connection errors
Adamant-im/adamant pull request #89
Opened 2024-12-16 21:42 UTC by yoxira

https://trello.com/c/l0PvLgan/97-check-adding-and-removing-new-peers

- Made removing and adding a new peer the same log level (`info`)
- Instead of removing a peer, multiple failed requests will change a peer state to `DISCONNECT`
  
  > Previously, the connection errors behavior was to remove the peer from the peers list. However, if the error happens due to a request-limiter policy or internet issues, the node only removes the peer temporarily until it rediscovers it in a second after removing, leading to spam in logs.

2024-12-17 00:00 UTC, yoxira commented
To do: move request success rate and request sample to a config file

2024-12-18 15:59 UTC, adamant-al commented
<img width="905" alt="image" src="https://github.com/user-attachments/assets/c0bebf8a-b238-46f5-a4b7-5fb13dc7b8b9" />

Firstly, init nodes added, and then others discovered.

```
http://162.55.32.80:36666/api/peers
```

Summary:
	•	Total Peers Count: 137
	•	Peers by Version:
	•	0.8.3: 95
	•	0.8.1: 20
	•	0.8.0: 10
	•	0.7.0: 2
	•	0.7.1: 1
	•	0.6.5: 9

Peers by State:
	•	Active (state: 2): 133
	•	Inactive (state: 1): 4

2024-12-18 21:44 UTC, bludnic requested changes

2024-12-18 21:44 UTC, bludnic commented on logic/peer.js
> +  return Math.round(successRate * 100) / 100;
Why not using just: `return Math.round(successRate)`?

2024-12-18 21:44 UTC, bludnic commented on modules/peers.js
> +Peers.prototype.isFrozen = function (ip, port) {
Add JSDoc

2024-12-18 21:44 UTC, bludnic commented on modules/transport.js
> + * @param {{ip: string, port: number, error?: string}} options
```suggestion
 * @param {{ peer: { ip: string, port: number }, error?: string }} options
```

2024-12-18 23:15 UTC, yoxira commented on modules/peers.js
> +Peers.prototype.isFrozen = function (ip, port) {
it's there..?

https://github.com/Adamant-im/adamant/blob/feat/peers/modules/peers.js#L308

2024-12-18 23:15 UTC, yoxira commented on logic/peer.js
> +  return Math.round(successRate * 100) / 100;
the rounding here is unnecessary, it's just for logs if we ever need one, and decimal numbers with double digits after the point just seem fancier

2024-12-18 23:25 UTC, bludnic approved these changes

2024-12-19 16:58 UTC, merged