feat: add `timestampMs` for transactions
Adamant-im/adamant pull request #93
Opened 2024-12-17 23:39 UTC by yoxira

https://trello.com/c/IN62zyEb/114-feat-verify-store-and-return-unixtimestamp-for-txs

2024-12-18 19:18 UTC, adamant-al commented on logic/transaction.js
> +  if (typeof trs.timestampMs !== 'number') {
Will previous txs/blocks be valid?
It's important to keep backward compatibility.

2024-12-18 19:18 UTC, adamant-al commented on logic/transaction.js
> +  if (Math.abs(trs.timestampMs - trs.timestamp * 1000) >= 1000) {
Will previous txs/blocks be valid?

2024-12-18 19:18 UTC, adamant-al commented on logic/transaction.js
> +  const currentTime = slots.getTime();
Returns time in seconds, not in ms, right?

2024-12-18 19:22 UTC, adamant-al commented
Ensure that

> A node will include `timestampMs` in responses, including socket.

2024-12-18 19:32 UTC, yoxira commented on logic/transaction.js
> +  const currentTime = slots.getTime();
yes

2025-02-01 19:00 UTC, yoxira commented
Test script using `adamant-api`:


```js
import {
  createSendTransaction,
  fees,
  createKeypairFromPassphrase,
  AdamantApi,
} from 'adamant-api';

const transaction = createSendTransaction({
  recipientId: RECIPIENT_ADDRESS,
  amount: fees.send,
  keyPair: createKeypairFromPassphrase(SENDER_PASSPHRASE),
});

transaction.timestampMs = transaction.timestamp * 1000;

const res = await api.post('transactions/process', {
  transaction,
});

console.log(res);
```

2025-02-01 19:13 UTC, yoxira commented
Now `timestampMs` isn't mandatory.

- `Transaction.prototype.verify` - checks a transaction retrieved from other blocks; may include old transactions.
- `Transactions.prototype.publish` - checks incoming transactions from users, verifying "fresh" unconfirmed transactions.

2025-02-05 21:07 UTC, bludnic commented on logic/transaction.js
> +    if (timestampMsDelta >= 1000) {
1000 -> const

2025-02-05 21:15 UTC, yoxira commented on logic/transaction.js
> +  }
the code was moved to `validateTimestampMs()`.

2025-02-09 10:05 UTC, adamantmm requested changes

2025-02-09 10:05 UTC, adamantmm commented on logic/transaction.js
> + * Validates the timestamp and timestampMs of a transaction to ensure they are within an acceptable range
If it's used for new txs only and not used for past txs validation (doesn't influence consensus), consider adding such a comment.

2025-02-09 10:06 UTC, adamantmm commented
> Now `timestampMs` isn't mandatory.
> 
> * `Transaction.prototype.verify` - checks a transaction retrieved from other blocks; may include old transactions.
> * `Transactions.prototype.publish` - checks incoming transactions from users, verifying "fresh" unconfirmed transactions.

Can you confirm that?

2025-02-11 16:03 UTC, bludnic commented on logic/transaction.js
> +  const error = this.verifyTimestamp(data);
It's a string containing the error message, or `undefined` if validation passed. A better name, in my opinion, would be `errorMessage`.

2025-02-13 14:03 UTC, yoxira commented on logic/transaction.js
> +  if (timestamp > INT_32_MAX) {
in 2087

The check for `int_32_max` was always there fyi https://github.com/Adamant-im/adamant/blob/master/logic/transaction.js#L647

2025-02-24 21:29 UTC, yoxira commented on logic/transaction.js
> +    return 'Invalid transaction timestamp. The timestamp is after the epoch time'
I removed it completely to avoid a possible consensus failure.

2025-02-24 21:34 UTC, yoxira commented
> Can you confirm that?

To be precise, `verify` is also called after receiving new transaction from the API, following `publish` and `objectNormalize` methods. And `publish` is only called when pushing transactions via the public API.

2025-02-24 21:44 UTC, yoxira commented
After changes:

 - Removes `timestampMs` from transactions before reaching a consensus. Important: the property is also removed before broadcasting to other nodes
 - After meeting a consensus, validates and includes `timestampMs` in the transactions
- Regardless of a consensus, checks if the transaction retrieved from the public API has a `timestamp` that is not in the future nor too far in the past

2025-02-24 21:47 UTC, yoxira commented
I suggest to use consensus code name in versions, e.g. `0.9.11-spaceship`

2025-02-25 09:12 UTC, adamant-al commented
> > Can you confirm that?
> 
> To be precise, `verify` is also called after receiving new transaction from the API, following `publish` and `objectNormalize` methods. And `publish` is only called when pushing transactions via the public API.

So what's the exact flow? E.g.,

Receiving a new tx from a client app via API (it's the first node which sees the tx):
1. one
2. two
3. ..

Receiving a new tx (current height) from another peer:
1. one
2. two
3. ..

Fetching a tx from another peer when arising/verifying blockchain from 0 height:
1. one
2. two
3. ..

Please add trace logging to each involved methods, include tx id, block height, if it's already included in block or not, what we are doing, and other reasonable info.

Maybe you also can add more tests.

Then you can run to verify it and check logs using testnet.

**It will help us to understand the process better and keep concensus.**

2025-02-25 09:24 UTC, adamant-al commented
> I suggest to use consensus code name for versioning, e.g. `0.9.11-spaceship`

Are speaking about package.json? Doesn't it break something?

2025-02-25 09:31 UTC, adamant-al commented
> After changes:
> 
> * Removes `timestampMs` from transactions before reaching a consensus. Important: the property is also removed before broadcasting to other nodes
> * After meeting a consensus, validates and includes `timestampMs` in the transactions
> * Regardless of a consensus, checks if the transaction retrieved from the public API has a `timestamp` that is not in the future nor too far in the past

My guess was to keep `timestampMs`, and benefit from having it even before new consensus arrives:

- When a new node accepts the tx with `timestampMs` from a client via API (`publish`), it can check/validate it, and decline, don't even broadcast it to other nodes. Is it how it's working now, broadcasting only valid txs?
- Skip validating `timestampMs` before `spaceship` activated when receiving a tx from another node (`verify`)
- Validate `timestampMs` everywhere after `spaceship` activated

Will it work?

2025-02-25 09:32 UTC, adamant-al requested changes

2025-02-25 09:32 UTC, adamant-al commented on helpers/slots.js
>     * @return {number} ADAMANT epoch time constant.
* @return {number} ADAMANT epoch time (passed since ADM blockchain creation) constant in sec.

Add also method and parameter description to JSDoc.

2025-02-25 09:32 UTC, adamant-al commented on logic/consensus/activationHeights.js
> +const consensusActivationHeights = {
Add comments with descriptions

2025-02-25 09:32 UTC, adamant-al commented on logic/transaction.js
> +  const timestampValidationError = this.validateTimestampWindow(data);
Add JSDoc to `Transaction.prototype.publish`
Include when it's called exactly.

Add comment when you call `validateTimestampWindow()`, what's the goal and consensus name when activated

2025-02-25 09:32 UTC, adamant-al commented on logic/transaction.js
> +Transaction.prototype.validateTimestampMs = function (trs) {
I'm still confused to have both `validateTimestampWindow()` and `validateTimestampWindow()`.

Consider creating a single function, you can use params what to check and what to skip.

2025-02-25 09:32 UTC, adamant-al commented on logic/transaction.js
> +  if (!this.scope.consensus.isActivated('spaceship')) {
See my comment about keeping `timestampMs`
https://github.com/Adamant-im/adamant/pull/93#issuecomment-2681306317

2025-02-25 13:39 UTC, yoxira commented on logic/transaction.js
> +  if (transactionSlotNumber > currentSlotNumber) {
> Is it a replacement for

yes

> Is slots.getSlotNumber() the same as slots.getSlotNumber(currentTime)?

yes, `currentTime` is reused so it's a separate variable to avoid calling `getTime()` twice

2025-02-25 13:41 UTC, yoxira commented on logic/transaction.js
> +  if (transactionSlotNumber < earliestValidSlotNumber) {
No, this check is only for transactions from the public API.

```js
  if (transactionSlotNumber < earliestValidSlotNumber) {
    throw `Transaction timestamp is more than ... seconds in the past`;
  }
```

2025-02-25 19:06 UTC, yoxira commented on logic/transaction.js
> +  const timestampValidationError = this.validateTimestampMs(trs);
No, it won’t affect consensus. I just accidentally changed the order of possible errors. Although, it makes sense to prioritize checks that require less resources

2025-02-25 19:06 UTC, yoxira commented on logic/transaction.js
> +Transaction.prototype.validateTimestampMs = function (trs) {
I removed both functions

2025-02-26 16:06 UTC, adamant-al commented on logic/transaction.js
> +  const timestampValidationError = this.validateTimestampMs(trs);
Let's move it back to have less changes?
I think we'll not save much on prioritizing.

2025-02-26 16:09 UTC, adamant-al commented on logic/consensus/activationHeights.js
> +  spaceship: 1_000_000,
```suggestion
  spaceship: 100_000_000,
```

We already have 45M blocks :)

2025-03-10 13:58 UTC, yoxira commented
Currently:
- `timestampMs` will be activated at height 100,000,000 ("spaceship" consensus), including validation and database storage
- Transactions received from the public API must not be older than 5 seconds or set in the future. This rule applies before the consensus activation

2025-03-10 15:22 UTC, adamantmm approved these changes

2025-03-10 15:23 UTC, adamant-al commented
@bludnic 
Please check this PR.

2025-03-10 15:39 UTC, adamant-al commented
> > I suggest to use consensus code name for versioning, e.g. `0.9.11-spaceship`
> 
> Are speaking about package.json? Doesn't it break something?

@yoxira

2025-03-10 15:40 UTC, adamant-al commented
> > > Can you confirm that?
> > 
> > 
> > To be precise, `verify` is also called after receiving new transaction from the API, following `publish` and `objectNormalize` methods. And `publish` is only called when pushing transactions via the public API.
> 
> So what's the exact flow? E.g.,
> 
> Receiving a new tx from a client app via API (it's the first node which sees the tx):
> 
> 1. one
> 2. two
> 3. ..
> 
> Receiving a new tx (current height) from another peer:
> 
> 1. one
> 2. two
> 3. ..
> 
> Fetching a tx from another peer when arising/verifying blockchain from 0 height:
> 
> 1. one
> 2. two
> 3. ..
> 
> Please add trace logging to each involved methods, include tx id, block height, if it's already included in block or not, what we are doing, and other reasonable info.
> 
> Maybe you also can add more tests.
> 
> Then you can run to verify it and check logs using testnet.
> 
> **It will help us to understand the process better and keep concensus.**

@yoxira 

Please describe.

2025-03-11 11:57 UTC, yoxira commented
> Are speaking about package.json? Doesn't it break something?

Right. Old nodes are not compatible with such version names but I think we can start using it after `spaceship` activation, as every node should be updated by this time

2025-03-11 12:00 UTC, yoxira commented
> you can run to verify it and check logs using testnet.

Does it make sense to have activation heights for consensus in a separate config file? E.g., for mainnet and testnet

2025-03-11 16:00 UTC, adamant-al commented
> > you can run to verify it and check logs using testnet.
> 
> Does it make sense to have activation heights for consensus in a separate config file? E.g., for mainnet and testnet

Hmm… Good point.
To test activation, we better move activation heights outside code, may be config is the best place.

@yoxira

2025-03-12 12:00 UTC, yoxira commented
@adamant-al 

Receiving a new tx from a client app via API (it's the first node that sees the tx):  
1. Creates a new transaction from the received data, validates the client's transaction properties (including `timestampMs`), and adds a transaction ID (`Logic->Transaction.prototype.publish` method).  
2. Processes the unconfirmed transaction as usual.

Receiving a new tx (current height) from another peer:  
1. Validates the transaction. If it's invalid, removes the peer.  
2. Processes the unconfirmed transaction as usual.

Fetching a tx from another peer when arising/verifying the blockchain from height 0:  
1. Validates the transaction. If it's invalid, removes the peer.  
2. Processes the unconfirmed transaction as usual but **verifies multiple transactions at a time**.

<h1></h1>

Processing an unconfirmed transaction flow:

1. First, `logic.transaction.process()` is called. It verifies the transaction ID and normalizes the sender ID.  
2. Then, the transaction is normalized. The `logic.transaction.objectNormalize()` method validates the transaction object against a schema and removes unnecessary properties, **including `timestampMs` before spaceship activation**.  
3. Finally, `logic.transaction.verify()` is called, verifying all properties such as `timestamp`, `timestampMs`, `signature`, etc.

2025-03-13 05:40 UTC, adamant-al commented
@yoxira

Thanks for the explanation.

I still have some questions.

> Validates the transaction…

What's the exact process? What functions does a node call?

> …If it's invalid, removes the peer.

Is the peer banned forever? For some time? Until node restart?

- Why the "Receiving a new tx from a client app via API (it's the first node that sees the tx)" doesn't have "Validates the transaction" step?

- When a node broadcast a tx to other nodes? After the "Processes the unconfirmed transaction as usual" step?

- Besides `objectNormalize()`, we have `normalize()`. Where is it used and what's the difference? Don't we add `timestampMs` there? Please add JSDoc for `normalize()`.

- Why do we have both `apply()` and `applyUnconfirmed()`? (same for `undo()`). What's the difference?

- Can you confirm there is no other tx entrance besides those three you've described?

2025-03-13 09:10 UTC, yoxira commented
@adamant-al 

> Validates the transaction... What's the exact process? What functions does a node call?

A node only calls `objectNormalize()` for schema validation of a received transaction.

> Is the peer banned forever? For some time? Until node restart?

I don't think nodes can ban peers (`BANNED` status is never applied). It just removes peer from the peer list until it rediscovers the peer again

> Why the "Receiving a new tx from a client app via API (it's the first node that sees the tx)" doesn't have "Validates the transaction" step?

Because the step is included in "processing unconfirmed transactions" flow. 

> When a node broadcast a tx to other nodes? After the "Processes the unconfirmed transaction as usual" step?

Right. 

> Besides `objectNormalize()`, we have `normalize()`. Where is it used and what's the difference? Don't we add `timestampMs` there? Please add JSDoc for normalize().

The `normalize()` method is only used for `POST /transactions/normalize` endpoint that should be deprecated.

> Why do we have both apply() and applyUnconfirmed()? (same for undo()). What's the difference?

"apply" methods change balances of the sender and recipient accounts. `applyUnconfirmed()` changes _unconfirmed balance_. Same goes for "undo" methods.

2025-03-13 09:27 UTC, yoxira commented
> Can you confirm there is no other tx entrance besides those three you've described?

When a node generates a new block, the transactions are taken from an already verified list, so everything must be OK

2025-03-13 16:17 UTC, adamant-al commented
@yoxira @bludnic 

So the "Receiving a new tx from a client app via API (1)" flow has one more pre-step "publish" compared to "Receiving a new tx from peers (2, 3)".

All of flows validates, normalizes, verifies new transactions.

**We better determine our approach for introducing blockchain changes:**

What do we have:

- Two points of Tx entrance
- The first (1) is when tx comes from a client app via API, includes `publish()`
- The second (2) is when a node gets a tx from another node. **This tx is supposed to be verified at least once.**
- Both ways run `process()`, `objectNormalize()`, `verify()`

It means in (1 - `publish()`) we can do any checks and it will not break consensus.

There is a possibility that a malicious node will broadcast a tx where checks in `publish()` may fail. ⟶ If there are important checks, we include them also in `verify()`.

Currently we have these checks in `publish()`:

- 'Transaction timestamp is in the future'
- `Transaction timestamp is more than ${constants.maxTransactionAgeSec} seconds in the past`

These checks are not in `verify()`, right? May be the reason is that developers didn't want to break consensus…

Now we also have a new check in `verify()`: `The difference between timestamp and timestampMs is greater than ${maxTimestampMsDelta}ms`.

What's our approach?

- Run same checks in `publish()` and `verify()` (after consensus activation)
- Run different checks in `publish()` and `verify()`
- Run all checks in `verify()`
- …

Probably running same checks in both functions is more secure and optimal, but how to implement it? Moving checks to `consensus.js`? Or introduce new functions like `timestampChecks(consensusSensitive?)`?

2025-03-13 16:42 UTC, yoxira commented
@adamant-al 

There is no point in adding the same checks in the `publish` method as in `verify` because the latter MUST be called after `publish`. Also, we can't include `publish`'s checks in the `verify` method because they depend on the current time. It's impossible to verify whether an old transaction is no more than 5 seconds old.

2025-03-13 16:47 UTC, yoxira commented
Regarding debug logs, I suggest making them in a separate PR. I think it's a good idea to use the debug library or a similar approach, allowing us to filter debug logs, e.g., using `DEBUG=loader npm run start`

2025-03-13 18:29 UTC, adamant-al commented
> @adamant-al
> 
> There is no point in adding the same checks in the `publish` method as in `verify` because the latter MUST be called after `publish`. Also, we can't include `publish`'s checks in the `verify` method because they depend on the current time. It's impossible to verify whether an old transaction is no more than 5 seconds old.

Will a client app receive an error text `The difference between timestamp and timestampMs is greater than ${maxTimestampMsDelta}ms.` if it's not in `publish()` but in `verify()`?

2025-03-14 03:26 UTC, yoxira commented
> Will a client app receive an error text `The difference between timestamp and timestampMs is greater than ${maxTimestampMsDelta}ms.` if it's not in `publish()` but in `verify()`?

@adamant-al Yes, as it does with `Invalid transaction timestamp. Timestamp is not in the int32 range` right now.

2025-03-14 04:24 UTC, adamant-al approved these changes
gw, lfg

2025-03-16 11:28 UTC, merged

2026-05-07 04:24 UTC, adamant-al commented
Tracking issue: #209

Issue URL: https://github.com/Adamant-im/adamant/issues/209

2026-06-14 11:37 UTC, metalisk commented
Follow-up: the global `maxTransactionAgeSec` admission rule introduced here is being narrowed to messaging types only in #235 (implementation: #236).

**Offline wallet note:** even after that change, types 8 and 9 still enforce the 5-second past window in `publish()`, so a future offline wallet remains blocked for chat messages and KVS updates unless clients re-sign before submission or admission policy is extended further. Non-messaging types are the intended beneficiaries of the scope change.