V0.9.0
Adamant-im/adamant pull request #95
Opened 2024-12-20 06:47 UTC by yoxira

- bump version
- update some dependencies
- fix tests for new feature

2024-12-22 19:01 UTC, adamant-al approved these changes

2024-12-22 20:14 UTC, adamant-al commented
Is this test failed?

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/28de653c-9938-47f6-8ace-7924c77cfe18" />

2024-12-22 20:16 UTC, adamant-al commented
Is it infinite loop?

<img width="548" alt="image" src="https://github.com/user-attachments/assets/87289874-1258-4cf7-8eca-864149bd0737" />

2024-12-22 20:30 UTC, adamant-al requested changes
Check tests

2024-12-23 05:08 UTC, bludnic approved these changes

2025-01-11 06:38 UTC, adamant-al commented
@yoxira 
The problem is still there. Bug: Node stucks on full test https://trello.com/c/NxuBZFJS

2025-02-09 17:22 UTC, adamant-al approved these changes

2025-02-09 17:22 UTC, adamant-al commented
@yoxira Please merge and create a PR to `master`

2025-02-13 13:39 UTC, merged